### ISSUE TITLE
enhance: Uneven spacing below the sharing button at the bottom of the article preview page

### ISSUE THREAD

**Issue by LiusCraft** [goplus/community#139]
page:
<https://hotst:port>/p/59
<https://hotst:port>/p/52

![image](https://github.com/goplus/community/assets/47062832/29fa2484-18a6-4916-8399-19d51c8e082f)

**Comment by Kasey0727** [comment]
page`https://hotst:port/p/59`
![image](https://github.com/goplus/community/assets/96371110/c0fec7c0-5f6c-42fd-af65-ffae2e2e4e7c)
![image](https://github.com/goplus/community/assets/96371110/8223630d-c7e8-4fdb-8123-02c2d7220855)
There seems to be no such bug to me.

**Comment by Kasey0727** [comment]
page: `https://hotst:port/p/59`

![image](https://github.com/goplus/community/assets/96371110/b224c29c-a34b-47f3-9f67-f63a222d7e16)
![image](https://github.com/goplus/community/assets/96371110/96922582-5262-49c0-9682-10c07eddb309)

There seems to be no such bug to me.

**Comment by IRONICBo** [comment]
@LiusCraft Please check it.

**Comment by LiusCraft** [comment]
The problem still exists, possibly related to resolution

**Comment by IRONICBo** [comment]
- http://goplus-community-dev.community.svc.jfcs-qa1.local:8080/p/59

Maybe it's caused by markdown style.

**Comment by Baihhh** [comment]
At present, the article detail page has been newly changed, and no similar problems have been found.
![image](https://github.com/goplus/community/assets/63110802/2778b893-e743-472a-b0d1-ea5d62bd6dc6)
