### ISSUE TITLE
UI: The icons seems too small, recommend to enlarge them

### ISSUE THREAD

**Issue by CarlJi** [goplus/community#156]
RT.
<img width="474" alt="image" src="https://github.com/goplus/community/assets/10810759/41efb08e-9fe1-45c4-bc67-4e47242ffcaa">

**Comment by Kasey0727** [comment]
![image](https://github.com/goplus/community/assets/96371110/376652d0-2378-4a61-bc88-59e603a53990)
Icons enlarged.
