### ISSUE TITLE
安全相关 Review

### ISSUE THREAD

**Issue by nighca** [goplus/community#225]
### 账号相关

* JWT 有效期决策（参考 cookie 有效期的设定）
* cookie httponly？
* cmd/gopcomm/yap/callback_yap.html & 其他页面中存放 usertoken 的不可见 input

### 其他

* Golang、Javascript 数据传递的潜在风险
  - cmd/gopcomm/yap/user_yap.html `.User.Id`
* URL 参数拼接的潜在风险
  - layout_yap.html `searchValue`
  - cmd/gopcomm/yap/home_yap.html `.Value`

**Comment by nighca** [comment]
@Baihhh 

* user_yap.html
* layout_yap.html

这两个页面的数据传递逻辑还没有调整？

另外处理 URL 参数的逻辑不太对，我在 https://github.com/goplus/community/pull/236#pullrequestreview-1921156607 评论了

> cmd/gopcomm/yap/callback_yap.html & 其他页面中存放 usertoken 的不可见 input

我看代码中的这个 input 都注释掉了，如果确实没用了的话建议直接删掉

> * JWT 有效期决策（参考 cookie 有效期的设定）
> * cookie httponly？

这俩应该还没处理，等都处理完了再关这个 issue 吧，我先 reopen

**Comment by nighca** [comment]
> 我先 reopen

目测我 reopen 不了， @IRONICBo 你应该可以？

**Comment by IRONICBo** [comment]
Fixed: https://github.com/goplus/community/pull/281
