### ISSUE TITLE
Bug: If the article starts with an image, it will fail after translation.

### ISSUE THREAD

**Issue by Baihhh** [goplus/community#230]
http://goplus-community-dev.community.svc.jfcs-qa1.local:8080/article/102

This is because the MD format of the image is split into two lines after translation, which cannot be recognized by the Markdown Viewer.

![image](https://github.com/goplus/community/assets/63110802/bdc23545-475e-4535-9af6-ae0d60bf7ac4)

![image](https://github.com/goplus/community/assets/63110802/a8324822-e62e-4864-9947-32a0b8cdce63)

**Comment by IRONICBo** [comment]
Fixed:
<img width="1457" alt="image" src="https://github.com/goplus/community/assets/47499836/3f8264bd-d090-43c0-ac7c-036457abb382">
