### ISSUE TITLE
bug(article/view-page): Translated Chinese articles, the list items of markdown have not been translated

### ISSUE THREAD

**Issue by LiusCraft** [goplus/community#232]
articleId: 96

result: 
![image](https://github.com/goplus/community/assets/47062832/f9df0fc8-8ea1-45d1-88a6-539d36554efe)

**Comment by LiusCraft** [comment]
@IRONICBo

**Comment by IRONICBo** [comment]
/assign @huangsihao7

We need to skip for uncommon markdown tags, and check the result here.
Please reach the id:96 markdown content in MySQL db to reach data.

**Comment by huangsihao7** [comment]
Create the same text, translation function is no problem，id:125
<img width="1293" alt="image" src="https://github.com/goplus/community/assets/53976072/3afc0165-8095-479c-be4b-2e7c457368d6">
