### ISSUE TITLE
bug(account/info): After login, need to refresh the page to have the correct user information.

### ISSUE THREAD

**Issue by LiusCraft** [goplus/community#233]
after login, no refresh page:
- [ ] userInfo error
- [ ] Unable click menu-> user profile to access user profile page

**Comment by IRONICBo** [comment]
Please comment here to describe your steps.

**Comment by LiusCraft** [comment]
My account question, @xhyqaq  ready to try repair

**Comment by LiusCraft** [comment]
set GOP_CASDOOR_ORGANIZATIONNAME：Correct organization name
