### ISSUE TITLE
bug(article/like): click article like for The number of likes will decrease.

### ISSUE THREAD

**Issue by LiusCraft** [goplus/community#234]
For example, the number of likes is 3, but it will be-1 after giving likes.

expect:
click after: +1 or -1

![img_v3_028m_1441b121-50a7-4085-8d34-38f231926a1g](https://github.com/goplus/community/assets/47062832/995d61e6-98fd-4b89-b846-3dab6f728038)

**Comment by LiusCraft** [comment]
add:
the bug is caused by account: Id 1224405920261623809

**Comment by xhyqaq** [comment]
The account has dirty data
