### ISSUE TITLE
‘go to add article’ button handling issues

### ISSUE THREAD

**Issue by tsingbx** [goplus/community#294]
Click go to add article in the video or other panel. There is no response. It automatically switches to the articlue panel.

**Comment by LiusCraft** [comment]
Try to log on to the website before writing an article

**Comment by tsingbx** [comment]
> Try to log on to the website before writing an article

I have logged in，and then click the button.

**Comment by LiusCraft** [comment]
@IRONICBo /label bug

@Kasey0727 @Baihhh

**Comment by IRONICBo** [comment]
Fixed.
